### ISSUE TITLE
Hiragana and Katakana Pitch accents are not showing up

### ISSUE THREAD

**Issue by bearclaw2020** [IllDepence/anki_add_pitch_plugin#16]
Hi, 

First let me say awesome add-on. Works really well with Kankji, but when I enter Hiragana or Katakana expressions, it doesn't seem to be able to find the pitch accent. Any thing I might be doing wrong with the set up? Are you also having this issue?

Example below

![image](https://user-images.githubusercontent.com/86618167/123693462-15bd0c80-d826-11eb-8402-8fec2aff3a75.png)
![image](https://user-images.githubusercontent.com/86618167/123693485-1fdf0b00-d826-11eb-912e-2b2e2eb2094b.png)

**Comment by IllDepence** [comment]
Hi @bearclaw2020 

glad you like the add-on. Unfortunately, going from the hiragana rendition of a word (that is usually written in kanji) to a pitch accent wouldn't be very practical. This is because there are plenty of words which have the same hiragana rendition, meaning the add-on would have to guess the word (or figure out that all or most of the possible words have the same pitch accent pattern). Prominent examples of words with identical kana rendition but different pitch accent patterns are for example 花 and 鼻, or 橋, 箸, and 端. But you also come across this in compounds such as 以外 and 意外.

Because of this, what the add-on does is look up the words you enter in a dictionary file ([this one](https://github.com/IllDepence/anki_add_pitch_plugin/blob/master/wadoku_pitchdb.csv)), where 世界, for example, only has an entry as 世界 but not せかい. Words that are typically written in katakana or hiragana, though, should work—e.g., トラック, ブロッコリー, マッチ, さじ, and うっとうしい.
