### ISSUE TITLE
Manual Pitch Addition

### ISSUE THREAD

**Issue by nepuuu** [IllDepence/anki_add_pitch_plugin#17]
Hi! I just wanna say thank you for this wonderful plug-in! Helps a lot!

I just want to ask how to add the hollow circle for the particle. I tried manually putting a pitch accent to 朝ご飯 「あさごはん」 so I put LHHLLL, but I guess the code associates one letter of H or L to a kana so an error came up. The hollow dot will be crucial specially for the 尾高 pattern, right?

Thank you!

**Comment by IllDepence** [comment]
Hi @nepuuu 

glad you like the plugin.

You're correct in the assumption that each letter H or L corresponds to one circle. This often also corresponds to one kana, but combined sounds like しょ or きゃ only have one circle, not two. (Side note: this is because one circle always corresponds to one mora, and combined sounds ([拗音](https://en.wikipedia.org/wiki/Y%C5%8Don)) use two kana for one mora.)

As for the pitch you want to manually set, it should actually work the way you describe. Here's the process in detail:

1. With your cursor in the field you want to add the pitch illustration to, click the *set pitch accent* button
2. Insert あさごはん for the reading ([screenshot](https://user-images.githubusercontent.com/1835279/130038677-a0e4bb97-538f-4289-a73b-5a06b1788c45.jpg))
3. Insert LHHLLL for the pitch; i.e. one for each mora/kana in あさごはん plus a last one for the hollow circle ([screenshot](https://user-images.githubusercontent.com/1835279/130038697-9d9179d9-105c-44dd-9664-6362f335120c.jpg))
4. The pitch illustration should appear ([screenshot](https://user-images.githubusercontent.com/1835279/130038711-d2fad312-9759-4912-923e-e3e04c516e7c.jpg))

If this doesn't resolve the problem and you still get an error, let me know what the error message is and we'll continue to investigate. ;)

**Comment by nepuuu** [comment]
Wow! Kinda weird that it works now :00

Thank you so much!
