### ISSUE TITLE
bugs in Anki 2.1.50beta: duplicate pitch accents when bulk adding

### ISSUE THREAD

**Issue by billzt** [IllDepence/anki_add_pitch_plugin#24]
The svg code of pitch accents is:
```
<!-- accent_start -->
<svg class="pitch" XXXXXX>XXXXXX</svg>
<!-- accent_end -->
```

In Anki 2.1.50beta, if you manually show the code in the card detail page, the `<!-- accent_start -->` part would disappear, resulting in code like this:
```
<svg class="pitch" XXXXXX>XXXXXX</svg>
<!-- accent_end -->
```

Therefore, if you conduct bulk adding, it considers no pitch accents in this field since the `<!-- accent_start -->` tag is absent and then it again adds duplicated pitch accents in the same field.

Here I give an example containing a single word "働く". The last filed containing pitch accents has no `<!-- accent_start -->` tag. The reason why it disappeared is unknown

[test.zip](https://github.com/IllDepence/anki_add_pitch_plugin/files/7932760/test.zip)

**Comment by billzt** [comment]
I suggest that when judging whether pitch accent has already exists in this field, don't depend on `<!-- accent_start -->`. Instead depend on `svg class="pitch"`

**Comment by IllDepence** [comment]
Thank you for the bug report.

Unfortunately it’s a bit more complicated. Apart from the detection of cards that already contain a pitch accent pattern, several other aspects would need to be considered to word around this weird behaviour that 2.1.50beta appears to introduce.

1. Most importantly, removing pitch annotation relies on the `<!-- accent_start -->` being present
2. There is a distinction between automatically added cards (`<!-- accent_start -->`) and manually added cards (`<!-- user_accent_start -->`)
3. If the reading and pitch field of a card are the same, a `<hr>` element is insered *before* the SVG
4. If Anki messes around with the HTML in cards, there’s no guarantee that the `class` attribute of the `<svg>` element will always appear first. What originally was inserted as `<svg class="pitch" viewBox="0 0 102 75" [...]>` might end up being changed to `<svg viewBox="0 0 102 75" class="pitch" [...]>` for example. 
5. Changing the start and end marker would introduce undesirable complexity because backwards compatibility to cards added before and after the switch would always have to be kept in mind.

That all being said, I’ll see if I can spot when/how the HTML comment removal behaviour was introduced to Anki. Maybe I can file a bug report on their side.
If not, it might be necessary to make the currently simple plugin code somewhat more complex in the sense that the pitch annotation is not simply handled as a text being inserted/swapped out/removed, but rather the card’s contets would need to be handled as HTML content (i.e. elements in a DOM), the plugin would need to make use of beautifulsoup (which, iirc, is used in Anki) etc. etc.

**Comment by IllDepence** [comment]
Hi,

I just tried to replicate the bug you’re describing, but for me the start marker is not disappearing.

Here’s the Anki version I’m testing on:

```
Version ⁨2.1.50 (db804d95)⁩
Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
```

and here is the behavior when viewing the HTML source:

1. [normal](https://user-images.githubusercontent.com/1835279/151676683-b6edc0b2-e5d5-4c5f-a506-4d025b20f662.jpg)
2. [viewing HTML source](https://user-images.githubusercontent.com/1835279/151676682-ba77e8d5-6870-4ae3-ae4c-fbd0fd6c5ac3.jpg)

**Comment by IllDepence** [comment]
Reported in the beta testing section of the Anki formus:

https://forums.ankiweb.net/t/anki-2-1-50-beta/15608/163

**Comment by billzt** [comment]
Thanks for your testing

**Comment by IllDepence** [comment]
Did some further testing in different versions. The behavior apparently was introduced in 2.1.45.
I therefore created a new issue (#25) and will close this one. Thanks again for making me aware of the problem.
