### ISSUE TITLE
Change size of pitch accent

### ISSUE THREAD

**Issue by KingHabib** [IllDepence/anki_add_pitch_plugin#30]
Hello, this addon is great and I love how it looks. One minor issue I have is that it takes quite a bit of space as seen here:
![image](https://user-images.githubusercontent.com/26579319/163033976-07642dea-d37f-4064-a3f9-288b180513af.png)

Is there any way I can change the size and/or margin of the pitch accent indicator?

Thanks.

**Comment by IllDepence** [comment]
Hi,
glad you like the add-on.

You can modify the appearance using CSS. To do so, go to Tools → Manage Note Types → <your Japanese card type> → Cards → Styling. In the text field there, add something like the following.

```
svg.pitch {
    height: 50px;
    margin-top: -30px;
}
```

The above would scale the pitch illustration itself to two thirds of the default size (50px instead of 75px), and reduce the margin on top by 30px. Simply play around with the numbers until you find something that you like.
