### ISSUE TITLE
Question: can I use furigana for the reading field?

### ISSUE THREAD

**Issue by yangmillstheory** [IllDepence/anki_add_pitch_plugin#40]
Hi - thanks for the great plugin.

I never stored the plain reading - pure kana - for cards from Yomitan, thinking that furigana would be enough (after all, the kana is embedded in there).

So, I've used the furigana field for the "reading" field that's required by this plugin, and it looks like the bulk add feature worked for me nonetheless, at least for the 20 or so cards I've manually inspected.

Question: what would happen in case I used something like 

![image](https://github.com/IllDepence/anki_add_pitch_plugin/assets/2729079/fa64c3f5-23da-4db0-a6b7-135eb211dd6c)

as the "reading" field to for the plugin? Note that in text format, this is HTML-like code.

**Comment by yangmillstheory** [comment]
NB: It'd be nice to write tests for the expected behavior, assuming they don't already exist.

**Comment by IllDepence** [comment]
Hi,
glad to hear you find the plugin useful.

**Short answer**: in case of your deck, the plugin defaults to the first entry it finds for the expression’s pitch accent. This will be no problem in most cases, but can lead to undesired results in a few edge cases.

**Long answer**: 

In the example you give the following happens:

0. Assuming your expression field has the content “気づく”,
1. The plugin looks for “気づく” in its [database](https://github.com/IllDepence/anki_add_pitch_plugin/blob/master/src/wadoku_pitchdb.csv).
2. It will find exactly one entry with reading “きづく” and pitch accent pattern “LHLL” 
3. Then there’s a step to determine the intended reading (but since there’s just one option in the database, that one will be chosen in the end).
    3.1 The plugin will take your reading field’s content (`<ruby>気<rt>き</rt></ruby>づく`) and look for a match in the readings it found in the database (i.e. きづく)
    3.2 No match will be found, so the first reading + pitch accent pattern きづく + LHLL will be chosen
4. The pitch accent pattern illustration will be generated using きづく + LHLL and added to the card 

An edge case where this could go wrong:

* Assume you have a card with expression field “汚れ” and reading field `<ruby>汚<rt>よ</rt></ruby>れ`.
* 汚れ can be read よごれ (with pattern LHHL) or けがれ (with pattern LHHH) 
* In the plugin’s database, the entry for けがれ appears first
* Since the reading field `<ruby>汚<rt>よ</rt></ruby>れ` can’t be matched to either よごれ or けがれ, the first database entry will be chosen by default and the pattern will be created for けがれ instead of よごれ
* If the reading field where just the plain text “けがれ”, the correct pattern would be created

---

Regarding tests: tests have long been on my radar but I haven’t found the time to make the necessary adjustments to the project/code base. If you’re interested in the topic, there are a few pointers regarding Anki plugins and testing:

* [pytest-anki](https://github.com/glutanimate/pytest-anki) - a [pytest](https://docs.pytest.org/) plugin that allows developers to write tests for their [Anki add-on](https://addon-docs.ankiweb.net/)
* [Anki-Connect](https://git.foosoft.net/alex/anki-connect) - an Anki plugin that uses pytest and tox
* [scottgigante/korean-support/pull/9](https://github.com/scottgigante/korean-support/pull/9) - a PR that adds unittests to an Anki plugin

**Comment by yangmillstheory** [comment]
Thanks for the explanation! I guess I'll just correct any pitch accent
mistakes manually when they come up.
